export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const CURRENT_WEATHER_DATA = "CURRENT_WEATHER_DATA";
export const CURRENT_WEATHER_DATA_SUCCESS = "CURRENT_WEATHER_DATA_SUCCESS";
export const CURRENT_WEATHER_DATA_ERROR = "CURRENT_WEATHER_DATA_ERROR";

export const MONTHLY_WEATHER_DATA = "MONTHLY_WEATHER_DATA";
export const MONTHLY_WEATHER_DATA_SUCCESS = "MONTHLY_WEATHER_DATA_SUCCESS";
export const MONTHLY_WEATHER_DATA_ERROR = "MONTHLY_WEATHER_DATA_ERROR";
